# GCB-Dockerfiles CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install python requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r tests/requirements.txt
            pip install -r tests/devRequirements.txt
      - run:
          name: Build Docker Images
          command: ./build-ci.sh
      - run:
          name: Run python code that tests the Docker Images
          command: |
            . venv/bin/activate
            nosetests
            ./test-ci.sh
      - deploy:
          name: Deploy Docker Images
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              ./deploy-ci.sh
            fi
