# GCB-Dockerfiles CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build Docker Images
          command: ./build-ci.sh
      - deploy:
          name: Deploy Docker Images
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              ./deploy-ci.sh
            fi
