FROM broadinstitute/picard
MAINTAINER Alejandro Barrera <alejandro.barrera@duke.edu>

# Adaptation of the Dockerfile provided by the Broad Institue \
#   (see https://hub.docker.com/r/broadinstitute/picard/~/dockerfile)

CMD ["java", "-jar", "/usr/picard/picard.jar"]
